# Introduction

This code slices and dices fixed income indices according to different criteria

# Import libraries

In [1]:
import pandas as pd

# functions

In [2]:
def wgh_dur_yld(df, criterium):
    df['dur*wght'] = df['Weight (%)'] * df['DUR_ADJ_MID']
    df['yld*wght'] = df['Weight (%)'] * df['YLD_YTM_MID']
    
    data = dict()

    gb = df.groupby(criterium)

    for group_name in gb.groups:
        df_industry = gb.get_group(group_name)
    
        dur = df_industry['dur*wght'].sum() / df_industry['Weight (%)'].sum()
        yld = df_industry['yld*wght'].sum() / df_industry['Weight (%)'].sum()
    
        data[group_name] = {} #  initialise data for 
        data[group_name]['dur'] = dur
        data[group_name]['wght'] = df_industry['Weight (%)'].sum()
        data[group_name]['yld'] = yld
    
    df_data = pd.DataFrame(data).transpose().round(2)
    df_data = df_data[['wght', 'dur', 'yld']]    
    
    return df_data

# Barclays Euro Aggregate Corporate

## Read data file

In [35]:
wd_input = 'C:/Users/Pascal/OneDrive/Python/Data/bonds/corp/'
df = pd.read_csv('{}barclays_eur_corp.csv'.format(wd_input),encoding = "ISO-8859-1")

## Industry sector

In [30]:
df_industry = wgh_dur_yld(df, 'INDUSTRY_SECTOR')
#df_payment_rank = wgh_dur_yld(df, 'PAYMENT_RANK')
#print(df_industry)
#print(df_payment_rank)
df_industry

                         wght   dur   yld
Basic Materials          3.44  4.80  0.88
Communications           9.01  5.40  1.17
Consumer, Cyclical       9.08  4.80  1.25
Consumer, Non-cyclical  15.75  5.56  0.92
Diversified              0.31  4.49  0.73
Energy                   4.43  5.10  0.92
Financial               41.66  4.51  1.23
Industrial               6.47  5.30  0.95
Technology               2.50  5.67  0.69
Utilities                7.35  5.17  1.01

## Payment Rank

In [27]:
df_payment_rank = wgh_dur_yld(df, 'PAYMENT_RANK')
df_payment_rank

                   wght   dur   yld
1st lien           0.62  4.64  1.18
Jr Subordinated    3.74  4.31  3.17
Secured            0.40  5.02  1.04
Sr Non Preferred   3.40  4.87  1.44
Sr Preferred       8.88  3.82  0.53
Sr Unsecured      75.14  5.17  0.90
Subordinated       7.82  4.46  2.50

## Ratings

In [32]:
df_ratings = wgh_dur_yld(df, 'RTG_MOODY')
df_ratings

          wght   dur   yld
A1        9.38  5.07  0.51
A1 *-     0.41  5.05  0.55
A2       10.58  5.08  0.95
A2 *-     0.06  9.87  1.26
A2u       0.03  3.80  0.27
A3        9.51  5.22  1.15
A3 *+     0.69  4.23  0.67
A3u       0.32  4.99  1.11
Aa1       0.52  5.70  0.43
Aa2       2.67  4.56  0.36
Aa3       8.17  4.32  0.36
Aa3 *-    0.08  4.68  0.88
Aaa       0.46  7.51  0.62
Ba1       0.84  4.21  2.06
Baa1     17.87  5.09  1.06
Baa1 *+   0.56  5.38  0.95
Baa1 *-   1.24  5.45  1.17
Baa1u     0.12  2.05  0.18
Baa2     14.03  5.02  1.41
Baa2 *+   0.21  4.63  0.83
Baa2 *-   0.05  6.16  2.05
Baa2u     0.13  4.85  3.80
Baa3      8.70  4.38  1.79
Baa3 *+   0.03  5.21  1.39
Baa3 *-   0.16  4.69  2.98
Baa3u     0.07  4.17  1.58
NR        1.46  4.16  0.86
WR        0.09  6.56  0.74

## Coupon types

In [36]:
df_cpn_type = wgh_dur_yld(df, 'CPN TYP')
df_cpn_type

              wght   dur   yld
FIXED        89.89  4.99  0.91
VARIABLE      9.91  4.45  2.82
ZERO COUPON   0.20  8.19  2.65

## tickers

In [25]:
df_ticker = wgh_dur_yld(df, 'TICKER')
df_ticker = df_ticker.sort_values(by='wght', ascending=False)
df_ticker

        wght   dur   yld
VW      2.22  5.14  2.17
BNP     1.76  4.78  1.05
BFCM    1.30  4.76  0.75
TOTAL   1.29  5.34  1.31
RABOBK  1.28  3.90  0.43
ACAFP   1.21  5.39  1.31
ORAFP   1.14  5.71  1.52
ABIBB   1.14  6.83  1.03
DAIGR   1.12  5.17  0.90
INTNED  1.09  4.43  1.08
BMW     1.06  3.89  0.53
JPM     1.02  4.99  0.66
DT      0.94  5.50  0.80
T       0.94  6.79  1.63
VOD     0.92  5.25  1.25
TELEFO  0.90  5.41  0.98
ENGIFP  0.90  6.35  1.18
BPCEGP  0.90  4.48  0.85
GS      0.88  5.26  1.22
ALVGR   0.87  5.00  2.03
SANFP   0.85  6.37  0.50
SOCGEN  0.85  4.04  0.93
WFC     0.83  5.27  0.83
ABNANV  0.82  3.43  0.71
BPLN    0.80  5.06  0.56
GE      0.80  6.81  2.02
HSBC    0.78  4.63  0.87
DGFP    0.75  5.87  0.65
ENELIM  0.74  5.03  1.07
BAC     0.69  4.23  0.67
...      ...   ...   ...
BFB     0.02  6.78  0.93
CAT     0.02  1.65 -0.01
ADJGR   0.02  5.11  2.14
SACEIM  0.02  5.16  4.15
PSON    0.02  5.85  1.53
LUMINO  0.02  2.59  1.41
RIKSHM  0.02  4.89  1.14
LGFP    0.02  1.05  0.12
APHTRN  0.02  5.96  1.39
PHNXLN  0.02  7.75  5.41
CRLOG   0.02  5.46  1.68
STBNO   0.02  3.48  5.14
ETHIAS  0.02  5.84  3.43
GMGAU   0.02  6.23  1.68
GSHIAV  0.02  1.74  2.67
TPEPW   0.02  7.38  2.74
AGSBB   0.02  7.03  3.68
TLGGR   0.02  5.50  1.43
COFCHD  0.02  4.48  2.22
TJRTGC  0.02  3.17  2.20
HAR     0.02  2.92  0.69
ALB     0.02  2.74  0.46
HELLA   0.02  4.83  0.86
METSO   0.02  4.88  0.80
MEOGR   0.02  3.84  2.44
SVEGNO  0.02  3.74  0.54
HRRLET  0.02  3.54  4.52
CCNORD  0.01  6.83  2.55
BANQUE  0.01  4.39  1.83
SWEMAT  0.01  5.40  1.36

[576 rows x 3 columns]

# Barclays Global High Yield

## Read data file

In [43]:
wd_input = 'C:/Users/Pascal/OneDrive/Python/Data/bonds/corp/'
df_hy = pd.read_csv('{}barclays_global_hy.csv'.format(wd_input),encoding = "ISO-8859-1")

## Currency

In [38]:
df_ccy = wgh_dur_yld(df_hy, 'CURRENCY')
df_ccy

      wght   dur   yld
CHF   0.06  3.89  2.98
EUR  14.78  3.74  4.29
GBP   1.88  3.77  7.12
SEK   0.03  4.15  3.27
USD  83.24  4.18  7.08

## currency USD

### Industry sector: USD

In [44]:
df_hy_USD = df_hy.loc[df_hy['CURRENCY'] == 'USD']                                          #filter df by ccy
df_hy_USD['Weight (%)'] = 100* df_hy_USD['Weight (%)'] / df_ccy.loc['USD', 'wght']         #rebase weight to 100%
df_hy_USD_industry = wgh_dur_yld(df_hy_USD, 'INDUSTRY_SECTOR')    #slice and dice df according wght, dur, yld
df_hy_USD_industry

D:\ananconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                         wght   dur   yld
Basic Materials          5.18  3.85  6.77
Communications          13.34  3.84  6.83
Consumer, Cyclical       9.35  3.81  6.59
Consumer, Non-cyclical  11.93  3.65  6.88
Diversified              0.20  3.37  6.22
Energy                  12.46  4.44  7.83
Financial               13.22  3.33  6.57
Government              21.11  5.80  7.85
Industrial               7.39  3.65  6.56
Technology               3.31  2.71  6.61
Utilities                2.51  3.72  6.68

### Payment Rank

In [39]:
df_payment_rank_hy = wgh_dur_yld(df_hy_USD, 'PAYMENT_RANK')
df_payment_rank_hy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                  wght   dur    yld
1.5 Lien          0.07  3.28  29.13
1st lien          8.51  3.18   7.20
2nd lien          2.34  2.68   9.30
3rd lien          0.04  0.67   9.42
Jr Subordinated   0.97  4.69   6.44
Secured           2.86  3.20   9.05
Sr Subordinated   0.86  2.91   6.18
Sr Unsecured     80.87  4.41   6.95
Subordinated      2.29  3.76   5.59
Unsecured         1.20  2.92   8.78

### Ratings

In [40]:
df_ratings_hy = wgh_dur_yld(df_hy_USD, 'RTG_MOODY')
df_ratings_hy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

          wght    dur    yld
(P)Ba1    0.03   6.58   4.43
B1       10.00   3.66   6.26
B1 *+     0.11   1.44   5.30
B1 *-     0.06   4.06   5.49
B2       12.28   4.22   7.71
B2 *+     0.13   0.48   5.00
B2 *-     0.05   3.22   6.09
B2u       0.05   2.84   6.82
B3       10.56   4.01   7.56
B3 *+     1.51   4.10   6.38
B3 *-     0.44   5.19   7.69
B3u       0.59   4.70   7.05
Ba1       6.39   4.68   5.35
Ba1 *+    0.01  10.44   5.39
Ba1u      0.04   4.20   5.30
Ba2      14.15   4.88   5.17
Ba2 *+    0.41   2.30   4.29
Ba2 *-    0.58   2.57   5.20
Ba2u      0.02   5.31   6.53
Ba3      16.91   4.33   5.53
Ba3 *+    0.05   3.70   4.82
Ba3 *-    0.10   3.61   5.63
Ba3u      0.03   5.90   8.03
Baa2      0.07   1.75   3.97
Baa3      3.44   5.86   5.60
C         0.49   2.92  40.91
Ca        0.38   2.70  27.10
Caa1      5.81   3.17   9.67
Caa1 *+   0.18   2.01   7.22
Caa1u     0.05   3.40   6.65
Caa2      3.28   3.56  11.36
Caa2 *+   0.09   0.09   5.84
Caa3      0.63   3.34  20.33
Caa3 *+   0.02   0.01  10.36
Caa3u     0.03   3.01  14.62
NR        0.81   4.99   8.62
WR        0.51   3.86   6.96

### Coupon types

In [45]:
df_cpn_type_hy = wgh_dur_yld(df_hy_USD, 'CPN TYP')
df_cpn_type_hy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

               wght   dur    yld
DEFAULTED      0.40  3.08  42.77
FIXED         97.25  4.19   6.90
FLAT TRADING   0.04  2.75  25.93
PAY-IN-KIND    0.37  2.74  10.23
STEP CPN       0.46  6.26   9.35
VARIABLE       1.49  3.78   7.30

### Tickers: USD

In [37]:
df_hy_USD_Tickers = wgh_dur_yld(df_hy_USD, 'TICKER')
df_hy_USD_Tickers = df_hy_USD_Tickers.sort_values(by='wght', ascending=False)
df_hy_USD_Tickers

D:\ananconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\ananconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

        wght    dur     yld
TURKEY  2.56   7.06    6.62
ARGENT  2.05   6.26    9.59
PETBRA  1.79   6.70    5.57
BRAZIL  1.57   7.95    4.70
S       1.22   4.07    6.07
LEBAN   1.05   5.05    9.24
CHTR    0.98   3.93    5.10
ECUA    0.90   4.20    9.13
BHCCN   0.88   3.19    6.48
SOAF    0.84   7.45    5.24
EGYPT   0.84   6.04    7.02
ARGBON  0.83   2.22    9.59
CSCHLD  0.83   3.30    4.01
TEVA    0.81   5.33    5.59
THC     0.80   3.16    5.25
UKRAIN  0.75   4.51    9.71
BHRAIN  0.74   5.43    5.67
DOMREP  0.72   7.25    5.79
OMAN    0.72   6.90    6.69
HCA     0.70   4.95    4.75
TMUS    0.58   2.57    5.20
NGERIA  0.56   7.61    7.46
INTEL   0.53   3.04    8.71
SRILAN  0.53   4.34    6.92
CTL     0.52   4.54    5.82
DISH    0.49   3.30    7.98
NAVI    0.49   3.22    5.52
ALLY    0.49   4.74    4.34
CYH     0.47   3.15   12.81
FCX     0.47   4.95    4.98
...      ...    ...     ...
BBBB    0.01   2.00   24.84
BAS     0.01   3.29   14.97
HIRIDG  0.01   3.25   29.34
ITWG    0.01   2.04   14.79
CFG     0.01   1.06    6.57
CNW     0.01   8.88    7.86
STON    0.01   1.95   13.94
NP      0.01   2.05    5.61
JCREWB  0.01   2.09    7.96
UNM     0.01  10.03    6.96
ODBR    0.01   2.08   55.47
CLRCN   0.01   4.85    7.31
OILCAS  0.01   9.10    6.31
TAST    0.01   0.20    7.14
TSQ     0.01   3.41    8.71
PARRFN  0.01   5.05    9.17
PANOCH  0.01   3.82   10.30
TAPENE  0.01   2.56   16.71
HOTT    0.01   0.31    9.13
HTGC    0.01   3.27    5.93
SYNCIM  0.01   2.20   15.46
ORBC    0.01   2.65    7.15
OPY     0.01   2.14    6.10
OPTOES  0.01   1.95   12.39
BIOS    0.01   1.77    9.79
IFMCOL  0.01   1.79    4.76
SWY     0.01   7.66    8.33
MICBAK  0.01   3.27    9.03
SUNASC  0.00   1.20  101.10
CCFI    0.00   3.97   42.73

[1209 rows x 3 columns]

## currency EUR

### Industry sector: EUR

In [ ]:
df_hy_EUR = df_hy.loc[df_hy['CURRENCY'] == 'EUR']
df_hy_EUR_industry = wgh_dur_yld(df_hy_EUR, 'INDUSTRY_SECTOR')
df_hy_EUR_industry

### Tickers: EUR

In [ ]:
################################################################################################

In [ ]:
data = dict()

gb = df.groupby('INDUSTRY_SECTOR')

for group_name in gb.groups:
    df_industry = gb.get_group(group_name)
    
    dur = df_industry['dur*wght'].sum() / df_industry['Weight (%)'].sum()
    yld = df_industry['yld*wght'].sum() / df_industry['Weight (%)'].sum()
    
    data[group_name] = {} #  initialise data for 
    data[group_name]['dur'] = dur
    data[group_name]['wght'] = df_industry['Weight (%)'].sum()
    data[group_name]['yld'] = yld
    
df_data = pd.DataFrame(data).transpose().round(2)
df_data = df_data[['wght', 'dur', 'yld']]
df_data

In [12]:
df_hy

,ISIN,Description,Par Value,Vendor Price,Market Value(USD),Weight (%),Unnamed: 6,DUR_ADJ_MID,CURRENCY,COUNTRY,...,INDUSTRY_GROUP,RTG_MOODY,NAME,ISSUE_DT,PAYMENT_RANK,PX DIRTY MID,YLD_YTM_MID,AMT_ISSUED,dur*wght,yld*wght
0,ARARGE03H413,ARGBON 8 ¾ 05/07/24,16455518,99.658944,1.639940e+07,0.691715,NaN,2.222842,USD,AR,...,Sovereign,NaN,REPUBLIC OF ARGENTINA,07/05/2014,Unsecured,99.057000,9.592826,1.645552e+10,1.537572,6.635497
1,US040114GX20,ARGENT 7 ½ 04/22/26,6497345,88.662000,5.913635e+06,0.249433,NaN,5.151715,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,12/04/2017,Sr Unsecured,90.102333,9.946383,6.497345e+09,1.285007,2.480954
2,US71647NAY58,PETBRA 5.999 01/27/28,5400614,100.717010,5.455536e+06,0.230111,NaN,6.832178,USD,NE,...,Oil&Gas,Ba2,PETROBRAS GLOBAL FINANCE,20/09/2018,Sr Unsecured,101.471269,5.840298,5.400614e+09,1.572156,1.343914
3,US67054KAA79,SFRFP 7 ? 05/01/26,5190000,96.047000,5.016736e+06,0.211602,NaN,5.419548,USD,FR,...,Media,B2,ALTICE FRANCE SA,11/04/2016,1st lien,97.077014,8.050937,5.190000e+09,1.146789,1.703596
4,US85207UAF21,S 7 ? 09/15/23,4250000,106.394000,4.661198e+06,0.196606,NaN,3.712862,USD,US,...,Telecommunications,B3 *+,SPRINT CORP,14/11/2014,Sr Unsecured,109.930625,6.207397,4.250000e+09,0.729971,1.220411
5,US040114GW47,ARGENT 6 ? 04/22/21,4497440,96.085000,4.418420e+06,0.186366,NaN,1.919731,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,12/04/2017,Sr Unsecured,97.989972,9.072608,4.497440e+09,0.357772,1.690823
6,US105756BV13,BRAZIL 4 ¼ 01/07/25,4300000,100.686990,4.348831e+06,0.183431,NaN,5.138411,USD,BZ,...,Sovereign,Ba2,FED REPUBLIC OF BRAZIL,01/11/2013,Sr Unsecured,101.428639,4.071554,4.300000e+09,0.942541,0.746847
7,XS1627599654,EVERRE 8 ¾ 06/28/25,4680476,88.294000,4.186048e+06,0.176564,NaN,4.584836,USD,CI,...,Real Estate,B2,CHINA EVERGRANDE GROUP,28/06/2017,Secured,89.847389,11.311431,4.680476e+09,0.809519,1.997196
8,US71647NAS80,PETBRA 7 ? 01/17/27,3728000,109.121000,4.089415e+06,0.172489,NaN,6.006342,USD,NE,...,Oil&Gas,Ba2,PETROBRAS GLOBAL FINANCE,17/01/2017,Sr Unsecured,109.985542,5.884537,4.000000e+09,1.036025,1.015015
9,US893647BE67,TDG 6 ¼ 03/15/26,3800000,102.115000,3.881690e+06,0.163727,NaN,4.306097,USD,US,...,Aerospace/Defense,NaN,TRANSDIGM INC,13/02/2019,Secured,102.568028,5.821027,4.000000e+09,0.705024,0.953058
10,US040114GL81,ARGENT 8.28 12/31/33,4274096,88.006000,3.805698e+06,0.160522,NaN,6.197107,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,29/11/2005,Sr Unsecured,88.728000,10.338158,3.965934e+09,0.994769,1.659497
11,US71647NAQ25,PETBRA 8 ¾ 05/23/26,3000000,117.500000,3.584792e+06,0.151204,NaN,5.424000,USD,NE,...,Oil&Gas,Ba2,PETROBRAS GLOBAL FINANCE,23/05/2016,Sr Unsecured,119.831583,5.729518,3.000000e+09,0.820130,0.866326
12,US71647NAV10,PETBRA 5.299 01/27/25,3508265,100.215000,3.525103e+06,0.148686,NaN,5.024823,USD,NE,...,Oil&Gas,Ba2,PETROBRAS GLOBAL FINANCE,20/09/2018,Sr Unsecured,100.789047,5.209046,3.508265e+09,0.747122,0.774514
13,US900123AW05,TURKEY 7 ? 02/05/25,3250000,104.124000,3.510532e+06,0.148072,NaN,4.783969,USD,TU,...,Sovereign,Ba3,REPUBLIC OF TURKEY,24/01/2005,Sr Unsecured,104.627292,6.488336,3.250000e+09,0.708370,0.960739
14,US040114HQ69,ARGENT 5 ? 01/11/28,4250000,79.497000,3.402204e+06,0.143502,NaN,6.411696,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,11/01/2018,Sr Unsecured,79.136458,9.509528,4.250000e+09,0.920094,1.364641
15,XS0205537581,ARGENT 2.26 12/31/38,5034916,59.037000,3.399565e+06,0.143391,NaN,10.071960,EUR,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,29/11/2005,Sr Unsecured,59.875111,7.916627,5.072556e+09,1.444230,1.135174
16,US105756BW95,BRAZIL 5 01/27/45,3550000,91.534000,3.258332e+06,0.137434,NaN,13.858577,USD,BZ,...,Sovereign,Ba2,FED REPUBLIC OF BRAZIL,01/08/2014,Sr Unsecured,91.972444,5.614619,3.550000e+09,1.904641,0.771640
17,US1248EPBT92,CHTR 5 ? 05/01/27,3250000,98.696000,3.255738e+06,0.137325,NaN,6.513408,USD,US,...,Media,B1,CCO HLDGS LLC/CAP CORP,06/02/2017,Sr Unsecured,100.648236,5.260904,3.250000e+09,0.894451,0.722452
18,US91831AAB70,BHCCN 5 ? 05/15/23,3250000,98.423000,3.246482e+06,0.136934,NaN,3.637486,USD,CA,...,Pharmaceuticals,B3,BAUSCH HEALTH COS INC,27/03/2015,Sr Unsecured,100.181847,6.244589,3.250000e+09,0.498096,0.855098
19,US761735AP42,REYNOL 5 ¾ 10/15/20,3136836,100.282000,3.205804e+06,0.135218,NaN,0.077669,USD,US,...,Packaging&Containers,B1,REYNOLDS GRP ISS/REYNOLD,28/01/2013,1st lien,102.300528,5.549599,3.249600e+09,0.010502,0.750408
20,XS1458514673,ECUA 10 ¾ 03/28/22,2878000,106.736000,3.189601e+06,0.134535,NaN,2.519841,USD,ED,...,Sovereign,NaN,REPUBLIC OF ECUADOR,28/07/2016,Sr Unsecured,109.669278,8.710019,2.878000e+09,0.339007,1.171803
21,US040114GK09,ARGENT 2 ½ 12/31/38,5296689,59.126000,3.181377e+06,0.134188,NaN,9.655871,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,29/11/2005,Sr Unsecured,59.483722,8.560538,5.313143e+09,1.295704,1.148723
22,US040114HL72,ARGENT 6 ? 01/26/27,3749835,84.422000,3.179292e+06,0.134100,NaN,5.739153,USD,AR,...,Sovereign,B2,REPUBLIC OF ARGENTINA,12/04/2017,Sr Unsecured,83.854833,9.948640,3.749835e+09,0.769622,1.334115
23,US900123CL22,TURKEY 6 03/25/27,3250000,95.200000,3.169833e+06,0.133701,NaN,6.121230,USD,TU,...,Sovereign,Ba3,REPUBLIC OF TURKEY,23/01/2017,Sr Unsecured,97.821667,6.744485,3.250000e+09,0.818416,0.901746
24,US91831AAC53,BHCCN 6 ? 04/15/25,3250000,94.981000,3.153237e+06,0.133001,NaN,4.905896,USD,CA,...,Pharmaceuticals,B3,BAUSCH HEALTH COS INC,27/03/2015,Sr Unsecured,97.419236,7.079754,3.250000e+09,0.652490,0.941616
25,US71647NAF69,PETBRA 4 ? 05/20/23,3117135,99.882000,3.145656e+06,0.132681,NaN,3.801673,USD,NE,...,Oil&Gas,Ba2,PETROBRAS GLOBAL FINANCE,20/05/2013,Sr Unsecured,101.295750,4.320943,3.500000e+09,0.504412,0.573309
26,US45824TBA25,INTEL 8 ½ 10/15/24,2950000,100.049000,3.053139e+06,0.128779,NaN,3.653296,USD,LX,...,Telecommunications,Caa2,INTELSAT JACKSON HLDG,19/09/2018,Sr Unsecured,103.699778,8.463585,2.950000e+09,0.470468,1.089933
27,US105756BY51,BRAZIL 5 ? 02/21/47,3000000,98.571000,3.038693e+06,0.128170,NaN,13.554226,USD,BZ,...,Sovereign,Ba2,FED REPUBLIC OF BRAZIL,28/07/2016,Sr Unsecured,101.653875,5.707230,3.000000e+09,1.737243,0.731495
28,US12543DAY67,CYH 6 ¼ 03/31/23,3100000,95.605000,3.036411e+06,0.128074,NaN,3.458666,USD,US,...,Healthcare-Services,Caa1,CHS/COMMUNITY HEALTH SYS,16/03/2017,1st lien,98.148056,7.476311,3.100000e+09,0.442964,0.957518
29,US105756BZ27,BRAZIL 4 ? 01/13/28,3000000,99.499000,2.997303e+06,0.126424,NaN,7.187504,USD,BZ,...,Sovereign,NaN,FED REPUBLIC OF BRAZIL,13/10/2017,Sr Unsecured,100.034347,4.685578,3.000000e+09,0.908673,0.592370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,XS1028948047,PIZEXP 8 ? 08/01/22,200000,50.500000,1.299400e+05,0.005481,NaN,2.444824,GBP,EN,...,Retail,Caa2,PIZZAEXPRESS FINANCING 1,31/07/2014,2nd lien,52.168750,33.094027,2.000000e+08,0.013400,0.181381
3304,XS0794787175,FOURSN 12 ¼ 06/15/20,175000,58.057667,1.298510e+05,0.005477,NaN,0.890968,GBP,GS,...,Healthcare-Services,C,ELLI INVESTMENTS LTD,28/06/2012,2nd lien,57.017000,69.527787,1.750000e+08,0.004880,0.380805
3305,US26874QAB68,ESV 7.2 11/15/27,150000,79.296000,1.216440e+05,0.005131,NaN,5.897507,USD,US,...,Oil&Gas,B3 *-,ENSCO INTERNATIONAL INC,25/11/1997,Sr Unsecured,82.475500,10.668999,1.500000e+08,0.030259,0.054741
3306,US708160BS43,JCP 7.4 04/01/37,312458,36.002000,1.210980e+05,0.005108,NaN,4.777750,USD,US,...,Retail,Caa2,JC PENNEY CORP INC,14/04/1997,Sr Unsecured,39.445222,21.187549,4.000000e+08,0.024404,0.108222
3307,US79970YAB11,SN 7 ¾ 06/15/21,600000,18.221000,1.170760e+05,0.004938,NaN,1.140373,USD,US,...,Oil&Gas,Caa2,SANCHEZ ENERGY CORP,18/07/2014,Sr Unsecured,19.288806,114.952865,6.000000e+08,0.005631,0.567658
3308,XS0940701807,INTGEN 7 ½ 06/30/21,93400,96.844000,1.167220e+05,0.004923,NaN,2.094859,GBP,NE,...,Electric,Ba3,INTERGEN NV,13/06/2013,Secured,98.348833,8.768460,1.750000e+08,0.010314,0.043169
3309,US42979BAA26,HIRIDG 8 ? 03/15/25,250000,42.866000,1.164100e+05,0.004910,NaN,3.251636,USD,US,...,Cosmetics/Personal Care,Caa3,HIGH RIDGE BRANDS CO,22/03/2017,Sr Unsecured,47.266681,29.344336,2.500000e+08,0.015966,0.144083
3310,XS1647645081,HEMABV 8 ½ 01/15/23,150000,67.889000,1.160550e+05,0.004895,NaN,2.975845,EUR,NE,...,Retail,Caa2,HEMA BONDCO II BV,20/07/2017,2nd lien,69.189389,20.535156,1.500000e+08,0.014567,0.100522
3311,US69352JAK34,TLN 6 12/15/36,200418,55.254000,1.127430e+05,0.004755,NaN,8.444838,USD,US,...,Electric,Caa1,TALEN ENERGY SUPPLY LLC,14/12/2006,Sr Unsecured,60.340333,11.385110,3.000000e+08,0.040159,0.054141
3312,XS0289810318,TSCOLN 5.2 03/05/57,72750,118.852000,1.126830e+05,0.004753,NaN,17.851290,GBP,EN,...,Food,Ba1,TESCO PLC,05/03/2007,Sr Unsecured,121.993395,4.168372,5.000000e+08,0.084845,0.019812
3313,USG6710EAL41,ODBR 7 ? 06/26/42,850000,13.213000,1.123100e+05,0.004737,NaN,1.579007,USD,CI,...,Engineering&Construction,C,ODEBRECHT FINANCE LTD,26/06/2012,Sr Unsecured,13.045500,59.024753,8.500000e+08,0.007480,0.279609
3314,XS1512736379,CAJAMA 9 11/03/26,100000,93.928000,1.087950e+05,0.004589,NaN,2.193581,EUR,SP,...,Banks,NaN,BANCO DE CREDITO SOCIAL,03/11/2016,Subordinated,96.228014,10.342499,1.000000e+08,0.010066,0.047461
3315,XS1071419524,GALAPG 5 ? 06/15/21,127029,73.153000,1.060570e+05,0.004473,NaN,1.971188,EUR,LX,...,Machinery-Diversified,B3,GALAPAGOS SA,30/05/2014,1st lien,74.823056,19.964875,2.000000e+08,0.008818,0.089311
3316,US72348XAC11,PINNOP 9 05/15/23,196301,51.683000,1.058710e+05,0.004466,NaN,2.788746,USD,US,...,Agriculture,Caa3,PINNACLE OPERATING CORP,10/03/2017,1.5 Lien,54.967500,29.172122,1.963010e+08,0.012453,0.130270
3317,XS1028960257,ECPG 6 ½ 04/01/21,80043,98.616000,1.033580e+05,0.004360,NaN,1.896523,GBP,LX,...,Diversified Finan Serv,B1 *-,CABOT FINANCIAL LUXEMBOU,27/03/2014,1st lien,101.472167,7.021525,1.750000e+08,0.008268,0.030611
3318,XS1694763142,BPOPAA 5 ? 10/06/27,100000,82.554000,9.537302e+04,0.004023,NaN,2.944653,EUR,IT,...,Banks,NaN,BANCA POP ALTO ADIGE,06/10/2017,Subordinated,85.389890,8.353669,1.000000e+08,0.011846,0.033605
3319,US110394AE39,BRS 6 ¼ 10/15/22,401535,20.105000,8.909400e+04,0.003758,NaN,1.922537,USD,US,...,Oil&Gas Services,Caa2,BRISTOW GROUP INC,12/10/2012,Sr Unsecured,23.044139,65.479754,4.500000e+08,0.007225,0.246068
3320,US42829LAE48,HXN 13 ¾ 02/01/22,225000,38.303000,8.738500e+04,0.003686,NaN,1.651742,USD,US,...,Chemicals,Caa3,HEXION INC,08/02/2017,1.5 Lien,38.127694,62.840492,2.250000e+08,0.006088,0.231620
3321,US268787AB41,EPENEG 7 ¾ 09/01/22,195419,38.290000,8.172500e+04,0.003447,NaN,2.235958,USD,US,...,Oil&Gas,Caa3,EP ENER/EVEREST ACQ FIN,27/11/2012,Sr Unsecured,45.875194,39.378636,3.490000e+08,0.007708,0.135742
3322,US099599AJ16,HXN 7 ? 02/15/23,188411,36.530000,7.624500e+04,0.003216,NaN,2.848155,USD,US,...,Chemicals,C,HEXION INC,11/02/1993,Sr Unsecured,52.151875,28.903134,2.500000e+08,0.009160,0.092951
3323,US86737NAA63,SUNASC 8 ¾ 04/01/22,425040,14.324000,7.472600e+04,0.003152,NaN,1.199380,USD,US,...,Computers,Caa2,SUNGARD AVAIL SERV CAP,31/03/2014,Sr Unsecured,19.016972,101.102354,4.250400e+08,0.003780,0.318663
3324,XS0435957682,AIB 12 ½ 06/25/35,78680,72.283000,7.268600e+04,0.003066,NaN,4.550837,GBP,IR,...,Banks,Ba1,ALLIED IRISH BANKS PLC,25/06/2009,Subordinated,73.532500,19.634578,3.682530e+08,0.013952,0.060197
3325,US12509JAA79,CCFI 10 ¾ 12/15/23,276940,25.279000,7.000800e+04,0.002953,NaN,3.971005,USD,US,...,Diversified Finan Serv,Caa2,CCF HOLDINGS LLC,12/12/2018,Sr Unsecured,26.130500,42.731722,2.769404e+08,0.011726,0.126182
3326,US90400GAA94,UPL 6 ? 04/15/22,170889,38.236000,6.925700e+04,0.002921,NaN,2.063526,USD,US,...,Oil&Gas,Caa3,ULTRA RESOURCES INC,12/04/2017,Sr Unsecured,40.648153,45.598079,7.000000e+08,0.006028,0.133202
3327,USG6710EAP54,ODBR 4 ? 04/25/25,518600,13.308000,6.901500e+04,0.002911,NaN,2.481696,USD,CI,...,Engineering&Construction,C,ODEBRECHT FINANCE LTD,25/04/2013,Sr Unsecured,13.015000,57.473907,5.500000e+08,0.007224,0.167307
3328,USG6710EAQ38,ODBR 5 ¼ 06/27/29,500000,12.603000,6.301500e+04,0.002658,NaN,2.540407,USD,CI,...,Engineering&Construction,C,ODEBRECHT FINANCE LTD,27/06/2014,Sr Unsecured,13.031000,46.936079,5.000000e+08,0.006752,0.124753
3329,US90400GAB77,UPL 7 ? 04/15/25,225000,25.596000,6.293500e+04,0.002655,NaN,2.911258,USD,US,...,Oil&Gas,Caa3,ULTRA RESOURCES INC,12/04/2017,Sr Unsecured,28.693458,40.287406,5.000000e+08,0.007728,0.106945
3330,US48019TAB08,JONE 6 ¾ 04/01/22,409148,12.279000,6.051900e+04,0.002553,NaN,1.200906,USD,US,...,Oil&Gas,Caa3,JONES ENERGY HLDGS/FIN,23/03/2015,Sr Unsecured,14.812750,109.551954,5.000000e+08,0.003065,0.279647
3331,XS1071420027,GALAPG 7 06/15/22,250000,18.008000,5.404901e+04,0.002280,NaN,1.749944,EUR,LX,...,Machinery-Diversified,Caa3,GALAPAGOS HOLDING SA,30/05/2014,1st lien,21.285944,75.249920,2.500000e+08,0.003989,0.171551
3332,XS1248518158,NEWLOK 8 07/01/23,176719,1.910000,8.831000e+03,0.000372,NaN,0.264978,GBP,EN,...,Retail,C,NEW LOOK SENIOR ISSUER,24/06/2015,2nd lien,4.566889,279.373840,2.000000e+08,0.000099,0.104063

In [23]:
df_hy_USD = df_hy.loc[df_hy['CURRENCY'] == 'USD']
df_hy_USD['Weight (%)'].sum()
#df_hy_USD

83.244170937

In [ ]:
df_financials = df_g_Industry.get_group('Financial')
df_financials

In [ ]:
data