In [1]:
import csv
import os
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('sample_data.csv', delimiter = ',')   #price data

In [5]:
def variable_moving_average(df, N):
    # N is the smoothing period
    

    VMA = 'VMA'+str(N)  # Column name
    df[VMA] = np.nan  # Initialise column with NaN


    # VI(Volatility Index)= STDEVP(last_N_prices)
    # see for stdev.p vs stdev.s --> https://stackoverflow.com/questions/52642200/pandas-variance-and-standard-deviation-result-differing-with-manual-calculation
    VI_1 = df.price.loc[0:N].std()
    VI = 'VI'+str(N)
    df[VI] = df.price.rolling(N).std(ddof=0)
    # ---------------------------------------------DONE

    
    # VMA[1]= Previous VMA value
    VMA_1 = df.price.loc[0:N-1].mean(); df[VMA][N-1] = VMA_1  # Initialise first VMA 
    #----------------------------------------------DONE


    # alpha = 2/(N+1)
    alpha = 2/(N+1)  # CHANGE THIS TO N
    #----------------------------------------------DONE


    # VMA = (alpha * VI * close) + (1 - (alpha * VI) * VMA[1])
    # Very slow. Very, very slow
    #for i in range(N, len(df)):
    for i in range(N, 1000):
        df[VMA][i] = (alpha * df[VI][i] * df.price[i]) + ((1 - (alpha * df[VI][i])) * df[VMA][i-1])
    # IDEA: Rolling.apply(func). See --> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.Rolling.apply.html
    #----------------------------------------------DONE

In [6]:
variable_moving_average(df, 20)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
df['VMA20'][20]
df.loc[: 200, ['time', 'price', 'VMA20', 'VI20']]

              time    price        VMA20       VI20
0    1546635719999  3772.60          NaN        NaN
1    1546635779999  3772.51          NaN        NaN
2    1546635839999  3772.78          NaN        NaN
3    1546635899999  3770.72          NaN        NaN
4    1546635959999  3773.31          NaN        NaN
5    1546636019999  3776.41          NaN        NaN
6    1546636079999  3778.33          NaN        NaN
7    1546636139999  3774.40          NaN        NaN
8    1546636199999  3778.37          NaN        NaN
9    1546636259999  3775.96          NaN        NaN
10   1546636319999  3781.43          NaN        NaN
11   1546636379999  3783.58          NaN        NaN
12   1546636439999  3778.91          NaN        NaN
13   1546636499999  3782.54          NaN        NaN
14   1546636559999  3785.35          NaN        NaN
15   1546636619999  3781.84          NaN        NaN
16   1546636679999  3777.99          NaN        NaN
17   1546636739999  3775.47          NaN        NaN
18   1546636799999  3775.63          NaN        NaN
19   1546636859999  3776.86  3777.249500   3.978694
20   1546636919999  3774.70  3776.307127   3.881119
21   1546636979999  3775.85  3776.144377   3.738303
22   1546637039999  3773.88  3775.351692   3.675707
23   1546637099999  3770.58  3773.675298   3.688868
24   1546637159999  3774.48  3773.953469   3.629656
25   1546637219999  3776.74  3774.915440   3.624829
26   1546637279999  3782.35  3777.581952   3.765976
27   1546637339999  3778.20  3777.798697   3.682280
28   1546637399999  3780.22  3778.654831   3.712632
29   1546637459999  3780.98  3779.480209   3.727240
..             ...      ...          ...        ...
171  1546645979999  3798.25  3798.076337   1.360291
172  1546646039999  3796.82  3797.973135   0.862522
173  1546646099999  3797.34  3797.921126   0.862522
174  1546646159999  3796.76  3797.823669   0.881302
175  1546646219999  3795.38  3797.572445   1.079462
176  1546646279999  3794.62  3797.233867   1.204110
177  1546646339999  3793.71  3796.745152   1.456215
178  1546646399999  3792.01  3795.937891   1.790068
179  1546646459999  3790.90  3794.866229   2.233564
180  1546646519999  3791.99  3794.214627   2.378746
181  1546646579999  3792.50  3793.811929   2.466033
182  1546646639999  3790.06  3792.827305   2.755531
183  1546646699999  3791.28  3792.404661   2.868055
184  1546646759999  3791.12  3792.043910   2.948548
185  1546646819999  3791.89  3792.000860   2.936975
186  1546646879999  3793.87  3792.507964   2.848687
187  1546646939999  3794.32  3792.978731   2.727900
188  1546646999999  3793.86  3793.197146   2.602335
189  1546647059999  3793.49  3793.264971   2.431797
190  1546647119999  3803.19  3796.155155   3.057616
191  1546647179999  3809.52  3801.844994   4.470184
192  1546647239999  3815.61  3810.206097   6.377882
193  1546647299999  3813.75  3812.736497   7.497159
194  1546647359999  3828.73  3828.390173  10.276898
195  1546647419999  3834.96  3836.531481  13.011565
196  1546647479999  3819.00  3813.867699  13.573851
197  1546647539999  3822.83  3826.012796  14.228882
198  1546647599999  3812.90  3808.317758  14.169205
199  1546647659999  3812.00  3813.211345  13.954179
200  1546647719999  3811.81  3811.381886  13.707772

[201 rows x 4 columns]

In [ ]:
def mm_cross_simple(df,col_price,mm_short,mm_long):
    mm_short_name = str(mm_short) + 'MA'
    mm_long_name = str(mm_long) + 'MA'
    signal_mm = mm_short_name + mm_long_name
    df[mm_short_name] = df[col_price].rolling(window=mm_short).mean()
    df[mm_long_name] = df[col_price].rolling(window=mm_long).mean()
    df[signal_mm] = np.where(df[mm_short_name] > df[mm_long_name], 1,-1)
    return df

In [ ]:
def return_cum_strat_last_el(df, mm_short, mm_long, mm_short2, mm_long2, plot_return=False):
    
    #col title in the df
    signal_ma = str(mm_short) + 'MA' + str(mm_long) + 'MA'
    signal_ma1 = str(mm_short2) + 'MA' + str(mm_long2) + 'MA'
    tc = .002      #transaction cost
    
    df['price'] = df['price'].astype(float)
    df['date'] = df['time']/1000                      #binance time is in milliseconds-> transform in seconds
    df['date'] = pd.to_datetime(df['date'], unit='s') #format binance date in readable date 

    #signal calcul
    df = mm_cross_simple(df,'price', mm_short, mm_long)     #add in df above: short_ma, long_ma, signal_mm
    df = mm_cross_simple(df,'price', mm_short2, mm_long2)   #add in df above: short_ma, long_ma, signal_mm
    
    df['signal'] = (df[signal_ma] + df[signal_ma1])/2                          #create df signal: sell if -1 and buy if +1
    df['signal_chg'] = np.where(df['signal'] != df['signal'].shift(1), 1,0)    #count signal change, then number of trades
    df['tc'] = df['signal_chg'] * tc                                           #calc transactions cost
    df['tc'] = df['tc'].cumsum()
    
    #return calculations
    df['return'] = (df['price'] / df['price'].shift(1))-1                      #calc returns per minute for the series
    df['cum_return'] = (1 + df['return']).cumprod() - 1                        #calc cumulated returns for the series
    df['strat_ret'] = df['return'] * df ['signal']                             #calc strategy returns per minute for the series
    df['cum_strat_ret'] = (1 + df['strat_ret']).cumprod() - 1                  #calc strategy cumulated returns
    df['cum_strat_ret_tc'] = df['cum_strat_ret'] - df['tc']                    #remove transactions costs

    if plot:
        df.plot(x = 'date', y='cum_strat_ret_tc', figsize=(20,5))                               #graph the strategy returns 
    
    return df['cum_strat_ret_tc'].iloc[-1]                     # last element of Series df[..]

In [ ]:
s=2
l=50
s2=800
l2=1900
return_cum_strat_last_el(df, s, l, s2, l2)

plt.plot(df['date'],df['price'])
plt.plot(df['date'],df[str(s)+'MA'])
plt.plot(df['date'],df[str(l)+'MA'])
plt.show()

plt.plot(df['date'],df['price'])
plt.plot(df['date'],df[str(s2)+'MA'])
plt.plot(df['date'],df[str(l2)+'MA'])
plt.show()

In [ ]:
# GENERATE RESULTS

# arguments
print_progress=False 
write_progress=True
print_result=False

# initialise data structures and helpers
a_dict = {}
short_values = []
long_values = []
cum_strat_values = []
try:
    os.remove('running_progress.csv')
except:
    pass

# run through combinations
for short in range(2,101, 2):
    for long in range(5,201, 5):
        if short < long and long - short < 10:
            for short2 in range(50,201, 10):
                for long2 in range(100,501, 25):
                    if short2 < long2:
                        last_cum_strat_value = return_cum_strat_last_el(df, short, long, short2, long2)
                        a_dict[last_cum_strat_value] = (short, long, short2, long2)
                        
                        if print_progress:
                            print(
                                'last_el_df_cum_strat:{},'.format(last_cum_strat_value) +
                                ' short:{},'.format(short) +
                                ' long:{},'.format(long) +
                                ' short2:{},'.format(short2) +
                                ' long2:{},'.format(long2))
                        if write_progress:
                            with open('running_progress.csv', 'a') as f:
                                writer = csv.writer(f)
                                writer.writerow([last_cum_strat_value, short, long, short2, long2])
if print_result:
    maximum = max(a_dict)
    print(
        'The highest cum_strat_value is {}, with'.format(maximum) +
        ' mm_short={},'.format(a_dict[maximum][0]) +
        ' mm_long={},'.format(a_dict[maximum][1]) +
        ' mm_short2={},'.format(a_dict[maximum][2]) +
        ' mm_long2={}'.format(a_dict[maximum][3]))

In [ ]:
# PRINT COMBINATION FOR MAXIMUM RETURN
maximum = max(a_dict)
print(
    'The highest cum_strat_value is {}, with'.format(maximum) +
    ' mm_short={},'.format(a_dict[maximum][0]) +
    ' mm_long={},'.format(a_dict[maximum][1]) +
    ' mm_short2={},'.format(a_dict[maximum][2]) +
    ' mm_long2={}'.format(a_dict[maximum][3]))